### PR TITLE
Aarch64+ppc64le

### PR DESCRIPTION
**Pull request by anjos**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I requested that this package is compiled for linux-aarch64 and linux-ppc64le, however the bot never accomplished this for unknown reasons (https://conda-forge.org/status/#current_migrations).  I'm triggering the PR myself in hopes it will work well.

### CODE REVIEW

**Comment by anjos** [comment]
@kynan - could you give this one some love and merge it?  Should be really quick - I appreciate you're busy.  Thanks a lot in advance!

**Comment by anjos** [comment]
@conda-forge/help-python: can somebody from the community review this one?  The sole reviewer is not responding.  Thanks in advance!

**Comment by saraedum** [comment]
> @conda-forge/help-python: can somebody from the community review this one? The sole reviewer is not responding. Thanks in advance!

Do you see any indication that @kynan is not responding? That person did not respond in two days or so. I would just wait a bit longer here.

**Comment by anjos** [comment]
I apologise for sounding hasty.  I'll wait.  I still have to go through another package (conda-forge/fancycompleter-feedstock) after this one is merged.  I hope that does not take long.

**Comment by anjos** [comment]
@saraedum: another 5 days have gone.  What is the policy regarding this? Is there one?  Should I add myself as a maintainer?

**Comment by saraedum** [comment]
I think this is the relevant bit of documentation:

https://conda-forge.org/docs/maintainer/maintainer_faq/#a-feedstock-has-been-abandoned-and-i-would-like-to-take-over-maintenance

**Comment by anjos** [comment]
@conda-forge-admin, please add user @anjos

**Comment by anjos** [comment]
@saraedum: I added myself as a maintainer for this feedstock.  It's been 9 days since the sole maintainer was contacted.  Could you then, please, consider merging this?  Thanks!

**Comment by saraedum** [comment]
> @saraedum: I added myself as a maintainer for this feedstock. It's been 9 days since the sole maintainer was contacted. Could you then, please, consider merging this? Thanks!

I am not a core member. I don't have permission to merge this.

**Comment by saraedum** [comment]
While not getting stuff merged for a week can be annoying, I would also not consider this repository abandoned.

In any case, more maintainers is almost always better, so I hope that somebody with the right permissions can take care of this one.

If you desperately need this package as a dependency outside of the conda-forge ecosystem, you can also build it locally and provide it in a separate channel.

**Review by saraedum — APPROVED** [review]

**Comment by anjos** [comment]
Can a @conda-forge/core member please consider merging this?  As per rules, it's been more than a week w/o a reaction from the sole maintainer.  I added myself as maintainer and would like to have this PR merged when possible.  Thanks in advance!

**Comment by kynan** [comment]
Sorry folks, didn't have a chance to check in my GH notifications in a while. Glad you got it sorted and 👍🏽 to adding yourself as a maintainer @anjos . Better to not rely on a SpoF :)

**Pull request merged**
